/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Whitend (https://sketchfab.com/whitend.3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-forest-a36f80984fc24bd8919cb10bc3cc3fa4
Title: Shiny Forest
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/assets/model/shinyForest/shiny_forest.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.33}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_0.geometry}
          material={materials.Ground}
          scale={27.2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree000_0.geometry}
          material={materials["tree.012_0"]}
          position={[-13.581, 2.888, 0.97]}
          rotation={[-0.072, -0.246, Math.PI]}
          scale={1.369}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3805_0.geometry}
          material={materials.BlueFlowers}
          position={[-13.581, 2.888, 0.97]}
          rotation={[1.825, -0.964, 2.514]}
          scale={[0.383, 0.757, 0.593]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree002_0.geometry}
          material={materials["tree.012_0"]}
          position={[-7.446, -6.32, 2.965]}
          rotation={[0.117, -0.285, Math.PI]}
          scale={1.461}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3806_0.geometry}
          material={materials.BlueFlowers}
          position={[-7.446, -6.32, 2.965]}
          rotation={[2.066, -0.951, 2.577]}
          scale={[0.409, 0.808, 0.633]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree003_0.geometry}
          material={materials["tree.012_0"]}
          position={[-6.456, 6.142, 2.54]}
          rotation={[-0.062, -0.195, -Math.PI]}
          scale={0.845}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3807_0.geometry}
          material={materials.BlueFlowers}
          position={[-6.456, 6.142, 2.54]}
          rotation={[1.764, -0.979, 2.428]}
          scale={[0.237, 0.467, 0.366]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree004_0.geometry}
          material={materials["tree.012_0"]}
          position={[-1.483, 9.973, 2.658]}
          rotation={[-0.022, 0.117, Math.PI]}
          scale={0.698}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3808_0.geometry}
          material={materials.BlueFlowers}
          position={[-1.483, 9.973, 2.658]}
          rotation={[1.329, -0.984, 1.861]}
          scale={[0.195, 0.386, 0.302]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree005_0.geometry}
          material={materials["tree.012_0"]}
          position={[0.659, 9.162, 2.504]}
          rotation={[-0.151, 0.107, Math.PI]}
          scale={0.837}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3809_0.geometry}
          material={materials.BlueFlowers}
          position={[0.659, 9.162, 2.504]}
          rotation={[1.214, -0.987, 1.878]}
          scale={[0.234, 0.463, 0.362]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree006_0.geometry}
          material={materials["tree.012_0"]}
          position={[3.866, -4.549, 4.544]}
          rotation={[0.09, 0.109, -Math.PI]}
          scale={1.391}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3810_0.geometry}
          material={materials.BlueFlowers}
          position={[3.866, -4.549, 4.544]}
          rotation={[1.453, -0.986, 1.875]}
          scale={[0.389, 0.769, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree007_0.geometry}
          material={materials["tree.012_0"]}
          position={[3.749, 8.46, 2.319]}
          rotation={[-0.272, 0.104, -Math.PI]}
          scale={1.276}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3811_0.geometry}
          material={materials.BlueFlowers}
          position={[3.749, 8.46, 2.319]}
          rotation={[1.099, -0.987, 1.885]}
          scale={[0.357, 0.706, 0.552]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree008_0.geometry}
          material={materials["tree.012_0"]}
          position={[4.696, 2.597, 3.854]}
          rotation={[-0.195, 0.149, Math.PI]}
          scale={1.218}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3812_0.geometry}
          material={materials.BlueFlowers}
          position={[4.696, 2.597, 3.854]}
          rotation={[1.109, -0.977, 1.804]}
          scale={[0.341, 0.674, 0.527]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree009_0.geometry}
          material={materials["tree.012_0"]}
          position={[6.419, -6.408, 3.907]}
          rotation={[0.172, 0.162, Math.PI]}
          scale={1.565}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3813_0.geometry}
          material={materials.BlueFlowers}
          position={[6.419, -6.408, 3.907]}
          rotation={[1.457, -0.973, 1.782]}
          scale={[0.438, 0.866, 0.677]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree010_0.geometry}
          material={materials["tree.012_0"]}
          position={[7.429, 11.881, 1.55]}
          rotation={[-0.075, -0.041, -Math.PI]}
          scale={1.078}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3814_0.geometry}
          material={materials.BlueFlowers}
          position={[7.429, 11.881, 1.55]}
          rotation={[1.517, -1, 2.149]}
          scale={[0.302, 0.596, 0.467]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree011_0.geometry}
          material={materials["tree.012_0"]}
          position={[10.22, -7.542, 3.015]}
          rotation={[0.2, 0.178, Math.PI]}
          scale={0.923}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3815_0.geometry}
          material={materials.BlueFlowers}
          position={[10.22, -7.542, 3.015]}
          rotation={[1.463, -0.968, 1.755]}
          scale={[0.258, 0.51, 0.399]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree012_0.geometry}
          material={materials["tree.012_0"]}
          position={[10.129, -1.593, 3.574]}
          rotation={[-0.127, 0.2, Math.PI]}
          scale={1.441}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlueFlowers3816_0.geometry}
          material={materials.BlueFlowers}
          position={[10.129, -1.593, 3.574]}
          rotation={[1.107, -0.962, 1.719]}
          scale={[0.404, 0.797, 0.624]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/src/assets/model/shinyForest/shiny_forest.glb");
